# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blivion.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 916)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Resources/Resources/Blimp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setProperty(".\\Resources", "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPlots = QtWidgets.QWidget()
        self.tabPlots.setObjectName("tabPlots")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabPlots)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mpl_window = QtWidgets.QWidget(self.tabPlots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_window.sizePolicy().hasHeightForWidth())
        self.mpl_window.setSizePolicy(sizePolicy)
        self.mpl_window.setObjectName("mpl_window")
        self.mpl_layout = QtWidgets.QVBoxLayout(self.mpl_window)
        self.mpl_layout.setContentsMargins(0, 0, 0, 0)
        self.mpl_layout.setObjectName("mpl_layout")
        self.verticalLayout_2.addWidget(self.mpl_window)
        self.tabWidget.addTab(self.tabPlots, "")
        self.tabResults = QtWidgets.QWidget()
        self.tabResults.setObjectName("tabResults")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabResults)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1131, 771))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tblResults = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblResults.sizePolicy().hasHeightForWidth())
        self.tblResults.setSizePolicy(sizePolicy)
        self.tblResults.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tblResults.setObjectName("tblResults")
        self.tblResults.setColumnCount(0)
        self.tblResults.setRowCount(0)
        self.horizontalLayout.addWidget(self.tblResults)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tblFitParams = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblFitParams.sizePolicy().hasHeightForWidth())
        self.tblFitParams.setSizePolicy(sizePolicy)
        self.tblFitParams.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tblFitParams.setObjectName("tblFitParams")
        self.tblFitParams.setColumnCount(0)
        self.tblFitParams.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tblFitParams)
        self.tblFittedCurve = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblFittedCurve.sizePolicy().hasHeightForWidth())
        self.tblFittedCurve.setSizePolicy(sizePolicy)
        self.tblFittedCurve.setObjectName("tblFittedCurve")
        self.tblFittedCurve.setColumnCount(0)
        self.tblFittedCurve.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tblFittedCurve)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tabResults, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1161, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Analysis = QtWidgets.QMenu(self.menuBar)
        self.menu_Analysis.setObjectName("menu_Analysis")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setEnabled(False)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_open = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Resources/Resources/mjs-open-data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon1)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Resources/Resources/mjs-save-data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save.setIcon(icon2)
        self.action_save.setObjectName("action_save")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.action_quit.setObjectName("action_quit")
        self.action_get_base = QtWidgets.QAction(MainWindow)
        self.action_get_base.setCheckable(True)
        self.action_get_base.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Resources/Resources/baseline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_get_base.setIcon(icon3)
        self.action_get_base.setObjectName("action_get_base")
        self.action_get_loads = QtWidgets.QAction(MainWindow)
        self.action_get_loads.setCheckable(True)
        self.action_get_loads.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Resources/Resources/loaded.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_get_loads.setIcon(icon4)
        self.action_get_loads.setObjectName("action_get_loads")
        self.action_get_association = QtWidgets.QAction(MainWindow)
        self.action_get_association.setCheckable(True)
        self.action_get_association.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Resources/Resources/association.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_get_association.setIcon(icon5)
        self.action_get_association.setObjectName("action_get_association")
        self.action_phase_boundaries = QtWidgets.QAction(MainWindow)
        self.action_phase_boundaries.setObjectName("action_phase_boundaries")
        self.action_association_model = QtWidgets.QAction(MainWindow)
        self.action_association_model.setObjectName("action_association_model")
        self.action_saturation_model = QtWidgets.QAction(MainWindow)
        self.action_saturation_model.setObjectName("action_saturation_model")
        self.action_reduce_n = QtWidgets.QAction(MainWindow)
        self.action_reduce_n.setEnabled(True)
        self.action_reduce_n.setObjectName("action_reduce_n")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.menu_File.addAction(self.action_open)
        self.menu_File.addAction(self.action_save)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_quit)
        self.menu_Analysis.addAction(self.action_get_base)
        self.menu_Analysis.addAction(self.action_get_loads)
        self.menu_Analysis.addAction(self.action_get_association)
        self.menuSettings.addAction(self.action_association_model)
        self.menuSettings.addAction(self.action_saturation_model)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.action_phase_boundaries)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.action_reduce_n)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Analysis.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.toolBar.addAction(self.action_open)
        self.toolBar.addAction(self.action_save)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_get_base)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_get_loads)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_get_association)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Blivion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPlots), _translate("MainWindow", "Plots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabResults), _translate("MainWindow", "Results"))
        self.menu_File.setTitle(_translate("MainWindow", "File"))
        self.menu_Analysis.setTitle(_translate("MainWindow", "&Analysis"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_open.setText(_translate("MainWindow", "Open data"))
        self.action_save.setText(_translate("MainWindow", "Save results"))
        self.action_quit.setText(_translate("MainWindow", "Quit"))
        self.action_get_base.setText(_translate("MainWindow", "Baseline"))
        self.action_get_loads.setText(_translate("MainWindow", "Loaded"))
        self.action_get_association.setText(_translate("MainWindow", "Association"))
        self.action_phase_boundaries.setText(_translate("MainWindow", "Set phase boundaries"))
        self.action_association_model.setText(_translate("MainWindow", "Set association model"))
        self.action_saturation_model.setText(_translate("MainWindow", "Set saturation model"))
        self.action_reduce_n.setText(_translate("MainWindow", "Reduce number of data points"))
        self.action_close.setText(_translate("MainWindow", "Close"))
        self.action_close.setToolTip(_translate("MainWindow", "Close data"))

import blivion_rc
